import pathlib

CHANNELS_OUT = 3
IMG_WIDTH = 640
IMG_HEIGHT = 480
MASK_GROWTH_EVERY_N_EPOCHS = 10
REFERENCE_LOGGING_FREQ = 5

DATA_DIR = pathlib.Path("data")
TRAIN_VAL_TEST_DIR = DATA_DIR / "processed"
REF_DIR = DATA_DIR / "ref"
